"""initial migration

Revision ID: 2430c1c7268b
Revises: 
Create Date: 2022-09-25 10:36:39.257579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2430c1c7268b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account_type')
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('account_type', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
