"""migration of products

Revision ID: 651c81f58e74
Revises: 9695a2f5b8ee
Create Date: 2022-09-26 12:45:08.468988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651c81f58e74'
down_revision = '9695a2f5b8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    op.drop_table('tag')
    op.add_column('user', sa.Column('liked_products', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'liked_products')
    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
