"""migration of products

Revision ID: e75ba517bf05
Revises: 651c81f58e74
Create Date: 2022-09-26 16:54:35.273164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75ba517bf05'
down_revision = '651c81f58e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sale_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sale_price')
    # ### end Alembic commands ###
